import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/layouts/Navbar";
import Footer from "./Components/layouts/Footer";

const montserrat = Montserrat({ 
  subsets: ["latin"],
  weight:["100","200","300","400","500","600","700","800","900",] 
});

export const metadata = {
  title: "Agrivista Farms",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
